(() => {
  const page = (location.pathname.split('/').filter(Boolean).pop() || 'index.html').replace('.html','');
  const css = document.createElement('link');
  css.rel='stylesheet'; css.href='n1-ux.css?v=20260821a'; css.dataset.aidmeN1='1';
  document.head.appendChild(css);

  const setBi = (el,no,en) => { if(!el) return; const n=el.querySelector('.lang-no'); const e=el.querySelector('.lang-en'); if(n) n.textContent=no; if(e) e.textContent=en; };
  const setAnchor = (a,href,no,en) => { if(!a) return; a.href=href; setBi(a,no,en); };
  const interestHref = (source) => `kontakt.html?spor=deltaker&fra=${encodeURIComponent(source)}#deltaker-interesse`;
  const routeMap = () => `<div class="n1-route-map" aria-label="Skjematisk rute fra Portugal til Santiago i Spania">
    <div class="n1-map-title"><strong><span class="lang-no">Portugal → Spania</span><span class="lang-en">Portugal → Spain</span></strong><span><span class="lang-no">skjematisk rute</span><span class="lang-en">schematic route</span></span></div>
    <svg viewBox="0 0 620 150" role="img" aria-label="Portugal til Santiago de Compostela">
      <path class="route-base" d="M55 105 C145 80 190 118 280 82 S420 62 555 42"/><path class="route-line" d="M55 105 C145 80 190 118 280 82 S420 62 555 42"/>
      <circle class="route-node" cx="55" cy="105" r="9"/><circle class="route-node" cx="307" cy="75" r="7"/><circle class="route-node" cx="555" cy="42" r="10"/>
      <text x="38" y="132">Portugal</text><text class="map-sub" x="262" y="112">grense / border</text><text x="430" y="25">Santiago · Spania</text><text class="map-sub" x="430" y="62">målgang / arrival</text>
    </svg></div>`;

  document.querySelectorAll('.three-steps .step').forEach((card,i)=>{
    if(card.querySelector('.n1-step-verb')) return;
    const verbs=[['Ve.','Go.'],['Sé.','Be.'],['Vive.','Live.']];
    const badge=document.createElement('span'); badge.className='n1-step-verb'; badge.innerHTML=`<span class="lang-no">${verbs[i]?.[0]||''}</span><span class="lang-en">${verbs[i]?.[1]||''}</span>`;
    const h3=card.querySelector('h3'); if(h3) h3.insertAdjacentElement('afterend',badge);
  });

  if(page==='index'){
    const heroP=document.querySelector('.hero-copy > p');
    if(heroP && !document.querySelector('.camino-clarifier')) heroP.insertAdjacentHTML('afterend','<div class="camino-clarifier"><strong>Camino Portugués · Portugal → Spania</strong><span class="lang-no">En virkelig vandring – og en arena for veien videre.</span><span class="lang-en">A real walk – and an arena for the way forward.</span></div>');
    const heroCta=document.querySelector('.hero .cta-row a.gold'); setAnchor(heroCta,interestHref('hero'),'Se om dette kan passe for meg','See if this could fit me');
    const ribbon=document.querySelector('.journey-ribbon');
    if(ribbon){ ribbon.classList.add('n1-three'); const items=[...ribbon.children]; if(items[3]) items[3].remove(); if(!document.querySelector('.n1-safety-foundation')) ribbon.insertAdjacentHTML('afterend','<div class="n1-safety-foundation"><strong><span class="lang-no">Trygghet følger alle tre steg</span><span class="lang-en">Safety follows all three stages</span></strong> · <span class="lang-no">frivillig · individuelt vurdert · tilpasset</span><span class="lang-en">voluntary · individually assessed · adaptable</span></div>'); }
    const cards=[...document.querySelectorAll('.three-steps .step')];
    setBi(cards[0]?.querySelector('.phase'),'Din retning + støtteplan','Your direction + support plan');
    setAnchor(cards[0]?.querySelector('.step-link'),'via.html','Se hva VÍA innebærer','See what VÍA involves');
    setAnchor(cards[1]?.querySelector('.step-link'),'ser.html','Se ruten og hvordan dagene fungerer','See the route and how the days work');
    setAnchor(cards[2]?.querySelector('.step-link'),'vida.html','Se hvordan oppfølgingen fungerer','See how follow-up works');
    const rs=document.querySelector('.route-shell');
    if(rs){ const h2=rs.querySelector('h2'); setBi(h2,'Fra Portugal til Santiago i Spania. Et landsskifte du går til fots.','From Portugal to Santiago in Spain. A border you cross on foot.'); const p=rs.querySelector('p:not(.eyebrow)'); setBi(p,'Camino Portugués er anbefalt hovedrute: ca. 230–270 km og rundt 14 vandredager, med rom for hvile og tilpasning. Andre ruter, lengder og etappedelinger kan vurderes når det er mer riktig for deltakeren.','Camino Portugués is the recommended main route: about 230–270 km and around 14 walking days, with room for rest and adaptation. Other routes, lengths and stage plans can be considered when they fit the participant better.'); if(!rs.querySelector('.n1-route-map')) rs.querySelector('div')?.insertAdjacentHTML('beforeend',routeMap()); const a=rs.querySelector('.btn'); setAnchor(a,'ruter.html','Se hele ruten','See the full route'); }
    const teaser=document.querySelector('.route-teaser');
    if(teaser && !document.querySelector('.n1-arrival-card')) teaser.insertAdjacentHTML('afterend',`<section class="n1-arrival-card"><div class="n1-arrival-photo"><img src="assets/santiago-team.webp" alt="Gruppe ved Santiago-katedralen"></div><div class="n1-arrival-copy"><p class="eyebrow"><span class="lang-no">Målgang</span><span class="lang-en">Arrival</span></p><h2><span class="lang-no">Målgang, mestring – og en ny begynnelse.</span><span class="lang-en">Arrival, mastery – and a new beginning.</span></h2><p><span class="lang-no">Målet er stort nettopp fordi veien dit er virkelig. Santiago skal ikke være et prestasjonskrav, men kan bli et konkret anker for det du faktisk har gjennomført – før VIDA tar erfaringen med hjem.</span><span class="lang-en">The goal matters because the road there is real. Santiago is not a performance demand, but can become a concrete anchor for what you actually completed – before VIDA carries the experience home.</span></p><a class="btn light" href="vida.html"><span class="lang-no">Se broen hjem</span><span class="lang-en">See the bridge home</span></a></div></section>`);
    document.querySelectorAll('a').forEach(a=>{ const t=a.textContent.toLowerCase(); if(t.includes('jeg vurderer å delta')||t.includes('meld interesse')||t.includes('ta kontakt')&&a.closest('.audience-card:not(.partner)')) setAnchor(a,interestHref('forside'),'Se om dette kan passe for meg','See if this could fit me'); if(t.includes('se deltakerreisen')) a.href='deltakere.html#deltakerreise'; });
  }

  if(page==='deltakere'){
    const heads=[...document.querySelectorAll('.section-head')];
    const journeySection=[...document.querySelectorAll('section')].find(s=>s.textContent.includes('Slik henger deltakerreisen sammen')); if(journeySection) journeySection.id='deltakerreise';
    const lead=heads.find(h=>h.textContent.includes('Er dette for meg?'))?.querySelector('.lead'); if(lead) setBi(lead,'AidMe VIDA er utviklet for mennesker med ressurser og kapasitet som har mistet mening, motivasjon, tilhørighet eller arbeidsretning – og som ønsker å prøve noe konkret i en trygg ramme.','AidMe VIDA is developed for people with resources and capacity who have lost meaning, motivation, belonging or direction in work – and want to try something concrete within a safe framework.');
    const callout=document.querySelector('.section .callout'); if(callout) callout.innerHTML='<strong><span class="lang-no">Et trygt «ikke nå» er også et godt resultat. Aktiv alvorlig rus, akutt psykisk risiko eller behov for omfattende klinisk oppfølging krever andre rammer enn dette deltakerløpet.</span><span class="lang-en">A safe “not now” is also a good outcome. Active severe substance misuse, acute mental-health risk or a need for extensive clinical support requires a different framework from this participant journey.</span></strong>';
    const cards=[...document.querySelectorAll('#deltakerreise .step')]; if(cards[0]) setBi(cards[0].querySelector('p'),'Vi finner ut hva du ønsker, hva du trenger for å føle deg trygg, og hva som skal være på plass før neste steg. Du trenger ikke ha hele planen klar.','We explore what you want, what you need to feel safe, and what should be in place before the next step. You do not need to have the whole plan ready.');
    const cc=document.querySelector('.contact-card'); if(cc){ const eye=cc.querySelector('.eyebrow'); setBi(eye,'Et enkelt første steg','A simple first step'); const p=cc.querySelector('p:not(.eyebrow)'); setBi(p,'Fortell bare nok til at vi kan forstå hva du er nysgjerrig på. Dette er en interessehenvendelse – ikke en påmelding eller vurdering av helse.','Tell us only enough to understand what you are curious about. This is an expression of interest – not enrolment or a health assessment.'); setAnchor(cc.querySelector('.btn'),interestHref('deltakerside'),'Se om dette kan passe for meg','See if this could fit me'); }
  }

  if(page==='via'){
    setBi(document.querySelector('.page-hero-copy p:not(.eyebrow)'),'Veivalg · Innsikt · Avklaring. Du trenger ikke ha hele planen klar. VÍA hjelper deg å finne ut hva du ønsker, hva som skal være på plass, og hva som gjør neste steg trygt og realistisk.','Pathfinding · Insight · Clarification. You do not need the whole plan ready. VÍA helps clarify what you want, what should be in place, and what makes the next step safe and realistic.');
    const mainHead=document.querySelector('.section .section-head h2'); setBi(mainHead,'VÍA gjør neste steg tydelig – uten at du må bestemme alt på forhånd.','VÍA makes the next step clearer – without requiring every decision up front.');
    const dark=document.querySelector('.panel.dark'); if(dark){ setBi(dark.querySelector('h3'),'Neste steg skal passe deg – ikke omvendt.','The next step should fit you – not the other way around.'); setBi(dark.querySelector('p'),'Vi ser på helheten sammen. Noen er klare for neste steg, noen trenger enkelte ting på plass først, og noen har mer nytte av en annen vei akkurat nå. Det er avklaring – ikke en dom.','We look at the whole picture together. Some are ready for the next step, some need a few things in place first, and some benefit more from another path right now. It is clarification – not judgement.'); const charge=dark.querySelector('.charge-copy>span'); if(charge) setBi(charge,'VÍA skal gjøre SER tryggere og mer realistisk – og VIDA-broen begynner allerede her.','VÍA should make SER safer and more realistic – and the VIDA bridge begins here.'); }
  }

  if(page==='ser'){
    const hero=document.querySelector('.page-hero-copy'); if(hero && !hero.querySelector('.n1-route-facts')) hero.querySelector('.cta-row')?.insertAdjacentHTML('beforebegin','<div class="n1-route-facts"><span>Portugal → Spania</span><span>ca. 230–270 km</span><span class="lang-no">ca. 14 vandredager</span><span class="lang-en">about 14 walking days</span></div>');
    const routeBtn=hero?.querySelector('.btn'); setAnchor(routeBtn,'ruter.html','Se ruten, dag for dag','See the route, day by day');
    const cc=document.querySelector('.contact-card'); if(cc){ setBi(cc.querySelector('p'),'Se hvordan hovedruten bygges opp dag for dag, hvilke etapper som kan tilpasses, og hvordan andre ruter kan brukes når de passer bedre.','See how the main route is built day by day, which stages can be adapted, and how other routes can be used when they fit better.'); const btns=cc.querySelectorAll('.btn'); if(btns[0]) setAnchor(btns[0],'ruter.html','Se hele ruten','See the full route'); }
  }

  if(page==='vida'){
    const strip=document.querySelector('.data-strip'); if(strip && !document.querySelector('.n1-new-via-note')) strip.insertAdjacentHTML('afterend','<p class="n1-new-via-note"><strong><span class="lang-no">Tre steg er hele løpet.</span><span class="lang-en">Three stages are the complete journey.</span></strong> <span class="lang-no">Hvis du senere trenger et nytt veivalg, kan en ny VÍA være et nytt startpunkt – ikke en forpliktelse.</span><span class="lang-en">If you later need a new direction, a new VÍA can be a new starting point – not an obligation.</span></p>');
    const cc=document.querySelector('.contact-card'); if(cc) setAnchor(cc.querySelector('.btn'),interestHref('vida'),'Se om dette kan passe for meg','See if this could fit me');
  }

  if(page==='ruter'){
    setBi(document.querySelector('.page-hero-copy .eyebrow'),'Ruten, dag for dag','The route, day by day'); setBi(document.querySelector('.page-hero-copy h1'),'En virkelig reise fra Portugal til Spania.','A real journey from Portugal to Spain.'); setBi(document.querySelector('.page-hero-copy p:not(.eyebrow)'),'Distanse, rytme og delmål gjør reisen konkret. Etappene kan tilpasses sikkerhet, dagsform og den enkeltes behov.','Distance, rhythm and milestones make the journey concrete. Stages can be adapted to safety, daily condition and individual needs.');
    const intro=document.querySelector('.route-intro > div'); if(intro){ setBi(intro.querySelector('h2'),'Camino Portugués – anbefalt hovedrute','Camino Portugués – recommended main route'); const p=intro.querySelector('p:not(.eyebrow)'); setBi(p,'Hovedruten går fra Porto til Santiago og gir en tydelig reise gjennom Portugal og inn i Spania: ca. 230–270 km og rundt 14 vandredager, pluss hvile- og styringsdager. Kortere varianter og andre Camino-ruter kan vurderes når de passer bedre.','The main route runs from Porto to Santiago and gives a clear journey through Portugal and into Spain: about 230–270 km and around 14 walking days, plus rest and coordination days. Shorter variants and other Camino routes can be considered when they fit better.'); if(!intro.querySelector('.n1-route-map')) intro.insertAdjacentHTML('beforeend',routeMap()); }
    const stages=document.querySelector('.stages .section-head h2'); setBi(stages,'Ruten, dag for dag.','The route, day by day.');
  }

  if(page==='kontakt'){
    setBi(document.querySelector('.page-hero-copy h1'),'Ett enkelt første steg.','One simple first step.'); setBi(document.querySelector('.page-hero-copy p:not(.eyebrow)'),'Er du nysgjerrig som deltaker, eller representerer du en partner? Velg riktig spor under. En deltakerinteresse er ikke påmelding eller godkjenning.','Curious as a participant, or representing a partner? Choose the relevant path below. Participant interest is not enrolment or approval.');
    const panels=[...document.querySelectorAll('.split .panel')];
    const partner=panels.find(p=>p.textContent.includes('Partnerdialog')); if(partner) setBi(partner.querySelector('p'),'Fortell kort hvilket behov dere ser, hvilken målgruppe det gjelder og hva dere håper en første pilot kan lære. Vi begynner der.','Briefly tell us what need you see, which target group it concerns and what you hope a first pilot could teach us. We begin there.');
    const participant=panels.find(p=>p.textContent.includes('Interesse som deltaker')); if(participant){ setBi(participant.querySelector('p'),'Du trenger ikke formulere hele historien din. Start med noen få kontaktopplysninger. Vi spør ikke om helseopplysninger her.','You do not need to explain your whole story. Start with a few contact details. We do not ask for health information here.'); setAnchor(participant.querySelector('.btn'),'#deltaker-interesse','Åpne kort interesseskjema','Open short interest form'); }
    const split=document.querySelector('.section .split'); if(split && !document.querySelector('#deltaker-interesse')) split.closest('section').insertAdjacentHTML('afterend',`<section class="n1-interest-wrap" id="deltaker-interesse"><div class="n1-interest-card"><p class="eyebrow"><span class="lang-no">For mulig deltaker</span><span class="lang-en">For a potential participant</span></p><h2><span class="lang-no">Se om dette kan passe for deg.</span><span class="lang-en">See if this could fit you.</span></h2><p class="lead"><span class="lang-no">Første steg er en kort interesse – ikke en påmelding. Vi trenger bare nok informasjon til å kunne svare og finne et logisk neste steg.</span><span class="lang-en">The first step is a short expression of interest – not enrolment. We only need enough information to reply and identify a logical next step.</span></p><form class="n1-interest-form" name="deltaker-interesse"><div class="n1-field"><label for="n1-name"><span class="lang-no">Fornavn</span><span class="lang-en">First name</span></label><input id="n1-name" name="first_name" autocomplete="given-name" required></div><div class="n1-field"><label for="n1-email">E-post</label><input id="n1-email" name="email" type="email" autocomplete="email" required></div><div class="n1-field"><label for="n1-phone"><span class="lang-no">Telefon (valgfritt)</span><span class="lang-en">Phone (optional)</span></label><input id="n1-phone" name="phone" type="tel" autocomplete="tel"></div><div class="n1-field"><label for="n1-contact"><span class="lang-no">Jeg foretrekker svar på</span><span class="lang-en">I prefer a reply by</span></label><select id="n1-contact" name="preferred_contact"><option value="email">E-post / Email</option><option value="phone">Telefon / Phone</option></select></div><p class="n1-form-note"><strong><span class="lang-no">Ikke skriv helseopplysninger eller andre sensitive personopplysninger her.</span><span class="lang-en">Do not enter health information or other sensitive personal data here.</span></strong> <span class="lang-no">Dette skjemaet brukes bare som første kontaktpunkt.</span><span class="lang-en">This form is only used as the first contact point.</span></p><div class="n1-form-actions"><button class="btn gold" type="submit"><span class="lang-no">Send interesse</span><span class="lang-en">Send interest</span></button><small><span class="lang-no">Dette er ikke påmelding eller en vurdering av om du kan delta.</span><span class="lang-en">This is not enrolment or an assessment of whether you can participate.</span></small></div></form></div></section>`);
  }
})();
