import { createClient } from 'npm:@supabase/supabase-js@2'

const CONTACT=['CONTACTED','NOT_CONTACTED','UNREACHABLE','NOT_APPLICABLE']
const NEXT_VIA=['NOT_NOW','CONSIDER_LATER','READY_FOR_NEW_VIA','NOT_APPLICABLE']
function allowedOrigin(origin:string){return ['https://my.aidme.no','https://demo.aidme.no','https://main--mycamino.netlify.app','https://demo-uat--mycamino-demo.netlify.app','http://localhost:8888','http://localhost:3000'].includes(origin)||/^https:\/\/deploy-preview-\d+--mycamino(?:-demo)?\.netlify\.app$/.test(origin)}
function cors(req:Request){const o=req.headers.get('origin')??'';return {'Access-Control-Allow-Origin':allowedOrigin(o)?o:'https://my.aidme.no','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json','Cache-Control':'no-store','Vary':'Origin'}}
function claims(t:string){const p=t.split('.')[1];if(!p)return{};const n=p.replace(/-/g,'+').replace(/_/g,'/');try{return JSON.parse(atob(n+'='.repeat((4-n.length%4)%4)))}catch{return{}}}
function active(g:any,pid:string,pilot:string|null){const now=new Date();return !g.revoked_at&&(!g.valid_from||new Date(g.valid_from)<=now)&&(!g.valid_until||new Date(g.valid_until)>now)&&(!g.participant_id||g.participant_id===pid)&&(!g.pilot_id||g.pilot_id===pilot)}
async function hasCapability(admin:any,userId:string,orgId:string,participantId:string,pilotId:string|null){const {data:g,error}=await admin.from('role_grants').select('role_code,participant_id,pilot_id,valid_from,valid_until,revoked_at').eq('user_id',userId).eq('organization_id',orgId);if(error)throw error;const roles=[...new Set((g??[]).filter((x:any)=>active(x,participantId,pilotId)).map((x:any)=>x.role_code))];if(!roles.length)return false;const {count,error:pe}=await admin.from('role_permissions').select('role_code',{head:true,count:'exact'}).in('role_code',roles).eq('capability','manage_participant_lifecycle');if(pe)throw pe;return (count??0)>0}
async function archiveBlocker(admin:any,participantId:string){const {count:tasks,error:te}=await admin.from('tasks').select('id',{head:true,count:'exact'}).eq('participant_id',participantId).in('status',['OPEN','IN_PROGRESS','WAITING']);if(te)throw te;if((tasks??0)>0)return 'ACTIVE_TASKS';const {count:incidents,error:ie}=await admin.from('incidents').select('id',{head:true,count:'exact'}).eq('participant_id',participantId).is('closed_at',null);if(ie)throw ie;if((incidents??0)>0)return 'OPEN_INCIDENT';const {count:sos,error:se}=await admin.from('sos_events').select('id',{head:true,count:'exact'}).eq('participant_id',participantId).neq('status','RESOLVED');if(se)throw se;if((sos??0)>0)return 'OPEN_SOS';return null}

Deno.serve(async(req:Request)=>{
 const headers=cors(req);if(req.method==='OPTIONS')return new Response('ok',{headers});if(req.method!=='POST')return new Response(JSON.stringify({error:'METHOD_NOT_ALLOWED'}),{status:405,headers})
 try{
  const ah=req.headers.get('Authorization')??'',token=ah.replace(/^Bearer\s+/i,'');if(!token)return new Response(JSON.stringify({error:'UNAUTHORIZED'}),{status:401,headers})
  const pk=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')??'{}').default,sk=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')??'{}').default;if(!pk||!sk)throw new Error('Missing keys')
  const uc=createClient(Deno.env.get('SUPABASE_URL')!,pk,{global:{headers:{Authorization:ah}},auth:{persistSession:false}}),admin=createClient(Deno.env.get('SUPABASE_URL')!,sk,{auth:{persistSession:false}})
  const {data:u,error:ue}=await uc.auth.getUser(token);if(ue||!u.user)return new Response(JSON.stringify({error:'UNAUTHORIZED'}),{status:401,headers});if((claims(token) as any).aal!=='aal2')return new Response(JSON.stringify({error:'MFA_REQUIRED'}),{status:403,headers})
  const b=await req.json(),participantId=String(b?.participantId??'').trim(),action=String(b?.action??'').trim().toUpperCase(),reason=String(b?.reason??'').trim().replace(/\s+/g,' '),contactStatus=String(b?.contactStatus??'').trim().toUpperCase(),nextViaAssessment=String(b?.nextViaAssessment??'').trim().toUpperCase();
  if(!participantId||!['ARCHIVE','RESTORE'].includes(action)||reason.length<8||reason.length>500||!CONTACT.includes(contactStatus)||!NEXT_VIA.includes(nextViaAssessment))return new Response(JSON.stringify({error:'INVALID_INPUT'}),{status:400,headers})
  const {data:p,error:pe}=await admin.from('participants').select('id,organization_id,code_name,stage,active').eq('id',participantId).maybeSingle();if(pe||!p)return new Response(JSON.stringify({error:'PARTICIPANT_NOT_FOUND'}),{status:404,headers})
  const {data:pp}=await admin.from('pilot_participants').select('pilot_id').eq('participant_id',participantId).eq('status','ACTIVE').order('joined_at',{ascending:false}).limit(1).maybeSingle(),pilotId=pp?.pilot_id??null
  if(!await hasCapability(admin,u.user.id,p.organization_id,participantId,pilotId))return new Response(JSON.stringify({error:'FORBIDDEN'}),{status:403,headers})
  const targetActive=action==='RESTORE';if(Boolean(p.active)===targetActive)return new Response(JSON.stringify({error:targetActive?'ALREADY_ACTIVE':'ALREADY_ARCHIVED'}),{status:409,headers})
  if(action==='ARCHIVE'){const blocker=await archiveBlocker(admin,participantId);if(blocker)return new Response(JSON.stringify({error:'ARCHIVE_BLOCKED',blocker}),{status:409,headers})}
  const now=new Date().toISOString();const {data:updated,error:updateError}=await admin.from('participants').update({active:targetActive,updated_at:now}).eq('id',participantId).eq('active',!targetActive).select('id,code_name,stage,active,updated_at').maybeSingle();if(updateError)throw updateError;if(!updated)return new Response(JSON.stringify({error:'STALE_STATE'}),{status:409,headers})
  const metadata={reason,contact_status:contactStatus,next_via_assessment:nextViaAssessment,pilot_id:pilotId,previous_active:!targetActive,new_active:targetActive}
  const eventType=action==='ARCHIVE'?'PARTICIPANT_ARCHIVED':'PARTICIPANT_RESTORED'
  const {error:we}=await admin.from('workflow_events').insert({organization_id:p.organization_id,participant_id:participantId,pilot_id:pilotId,actor_user_id:u.user.id,event_type:eventType,from_stage:p.stage,to_stage:p.stage,source_type:'participant_lifecycle',source_id:participantId,metadata});if(we)throw we
  const {error:ae}=await admin.from('audit_events').insert({organization_id:p.organization_id,actor_user_id:u.user.id,action:eventType,resource_type:'participant',resource_id:participantId,participant_id:participantId,purpose:'participant_lifecycle',metadata});if(ae)throw ae
  return new Response(JSON.stringify({ok:true,participant:updated}),{status:200,headers})
 }catch(error){console.error(error);return new Response(JSON.stringify({error:'PARTICIPANT_LIFECYCLE_FAILED'}),{status:500,headers})}
})
