(()=>{
'use strict';
const BAD_SORT="const ordered=[...open].sort((a,b)=>({RED:0,YELLOW:1,GREEN:2}[severity(a)]-({RED:0,YELLOW:1,GREEN:2}[severity(b)])||new Date(a.due_at||'2999')-new Date(b.due_at||'2999'));";
const GOOD_SORT="const rank={RED:0,YELLOW:1,GREEN:2};const ordered=[...open].sort((a,b)=>(rank[severity(a)]-rank[severity(b)])||(new Date(a.due_at||'2999')-new Date(b.due_at||'2999')));";
const BAD_TASK=`async function updateTaskStatus(status){
  const t=tasks.find(x=>x.id===selectedTaskId);if(!t)return;$('#taskDialogMessage').textContent='Lagrer…';const {error}=await client.from('tasks').update({status,updated_at:new Date().toISOString()}).eq('id',t.id);if(error){$('#taskDialogMessage').textContent='Kunne ikke oppdatere oppgaven med din tilgang.';return}t.status=status;$('#taskDialog').close();renderAll();
}`;
const GOOD_TASK=`async function updateTaskStatus(status){
  const t=tasks.find(x=>x.id===selectedTaskId);if(!t)return;$('#taskDialogMessage').textContent='Lagrer…';const {data,error}=await client.functions.invoke('task-command',{body:{taskId:t.id,status}});if(error||data?.error){$('#taskDialogMessage').textContent='Kunne ikke oppdatere oppgaven med din tilgang.';return}t.status=data?.task?.status||status;$('#taskDialog').close();renderAll();
}`;
const BAD_FORMS=`function renderForms(){const phaseFor={info_before_via:'VÍA',interest_referral:'VÍA',via_roadmap:'VÍA',individual_go_no_go:'VÍA',participant_agreement:'VÍA',pilot_go:'VÍA/SER',ser_daily:'SER',incident:'SER',vida_plan:'VIDA',pilot_evaluation:'VIDA'};$('#formLibrary').innerHTML=formDefs.map((f,i)=>\`<article class="form-module"><span class="num">\${String(i).padStart(2,'0')}</span><h3>\${escapeHtml(f.title_no)}</h3><p>\${escapeHtml(f.scope==='staff'?'Arbeidsflate for navngitt rolle/ansvar.':f.scope==='participant_staff'?'Deltaker og ansvarlig medarbeider – etter tilgang.':'Deltakerrettet steg.')}</p><div class="meta"><span>\${escapeHtml(phaseFor[f.key]||'VÍA/SER/VIDA')}</span><span>\${escapeHtml(f.scope)}</span></div></article>\`).join('')}`;
const GOOD_FORMS=`function renderForms(){const phaseFor={info_before_via:'VÍA',interest_referral:'VÍA',via_roadmap:'VÍA',individual_go_no_go:'VÍA',participant_agreement:'VÍA',pilot_go:'VÍA/SER',ser_daily:'SER',incident:'SER',vida_plan:'VIDA',pilot_evaluation:'VIDA'},participant=selectedParticipantId||ownParticipant()?.id||'';$('#formLibrary').innerHTML=formDefs.map((f,i)=>\`<a class="form-module" style="text-decoration:none;color:inherit" href="./form-runner.html?key=\${encodeURIComponent(f.key)}\${participant?'&participant='+encodeURIComponent(participant):''}"><span class="num">\${String(i).padStart(2,'0')}</span><h3>\${escapeHtml(f.title_no)}</h3><p>\${escapeHtml(f.scope==='staff'?'Arbeidsflate for navngitt rolle/ansvar.':f.scope==='participant_staff'?'Deltaker og ansvarlig medarbeider – etter tilgang.':'Deltakerrettet steg.')}</p><div class="meta"><span>\${escapeHtml(phaseFor[f.key]||'VÍA/SER/VIDA')}</span><span>Åpne →</span></div></a>\`).join('')}`;
const fallbacks=['https://unpkg.com/@supabase/supabase-js@2/dist/umd/supabase.js','https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js'];
const SUPABASE_URL='https://ibloovohuhrceivrvhvn.supabase.co';
const SUPABASE_KEY='sb_publishable_JtNmgzTLlepPhKDCVsn6CA_Vk7BCClv';
let opsClient=null,opsBusy=false,lastEnhancedParticipant=null;
function showFailure(text){const loading=document.querySelector('#loading'),auth=document.querySelector('#authView'),msg=document.querySelector('#authMessage');loading?.classList.add('hidden');auth?.classList.remove('hidden');if(msg)msg.textContent=text;console.error('[AidMe VIDA hotfix]',text)}
function loadScript(src,ms=5000){return new Promise((resolve,reject)=>{const s=document.createElement('script');let done=false;const t=setTimeout(()=>{if(done)return;done=true;s.remove();reject(new Error('timeout'))},ms);s.src=src;s.async=true;s.onload=()=>{if(done)return;done=true;clearTimeout(t);resolve()};s.onerror=()=>{if(done)return;done=true;clearTimeout(t);reject(new Error('load'))};document.head.appendChild(s)})}
async function ensureSupabase(){if(window.supabase?.createClient)return;for(const src of fallbacks){try{await loadScript(src);if(window.supabase?.createClient)return}catch{}}throw new Error('Sikker innloggingsmodul kunne ikke lastes')}
function addNavLink(nav,id,num,label,href){if(!nav||document.getElementById(id))return;const a=document.createElement('a');a.id=id;a.className='nav-item';a.href=href;a.innerHTML=`<span class="nav-num">${num}</span><b>${label}</b>`;nav.appendChild(a)}
function addMenuLink(menu,id,label,href,beforeLast=false){if(!menu||document.getElementById(id))return;const a=document.createElement('a');a.id=id;a.href=href;a.textContent=label;a.style.cssText='display:block;padding:10px 11px;border-radius:10px;color:inherit;text-decoration:none';beforeLast?menu.insertBefore(a,menu.lastElementChild):menu.insertBefore(a,menu.firstElementChild)}
async function installOpsUi(){
  try{
    opsClient=opsClient||supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
    const nav=document.querySelector('#mainNav');addNavLink(nav,'guideNav','00','Slik fungerer det','./guide.html');addNavLink(nav,'intakeNav','02+','Interesse / VÍA','./intake.html');addNavLink(nav,'ownersNav','02A','Ansvar / eiere','./owners.html');addNavLink(nav,'notificationsNav','N','Varsler','./notifications.html');addNavLink(nav,'auditNav','07A','Revisjon','./audit.html');addNavLink(nav,'sosNav','10','Hjelp & SOS','./sos.html');
    const menu=document.querySelector('#userMenu');addMenuLink(menu,'userGuideLink','Slik fungerer reisen','./guide.html');addMenuLink(menu,'userNotificationLink','Varsler','./notifications.html');addMenuLink(menu,'userSosLink','Hjelp & SOS','./sos.html',true);
    const admin=document.querySelector('#adminLink');const {data:{session}}=await opsClient.auth.getSession();if(!session)return;
    const {data:grants}=await opsClient.from('role_grants').select('role_code,revoked_at,valid_until').eq('user_id',session.user.id);const active=(grants||[]).filter(g=>!g.revoked_at&&(!g.valid_until||new Date(g.valid_until)>new Date()));const intakeRole=active.some(g=>['via_owner','program_lead'].includes(g.role_code)),ownerRole=active.some(g=>['project_owner','via_owner','clinical_professional'].includes(g.role_code)),isAdmin=active.some(g=>g.role_code==='system_admin');const intake=document.querySelector('#intakeNav'),owners=document.querySelector('#ownersNav'),audit=document.querySelector('#auditNav');if(intake)intake.classList.toggle('hidden',!intakeRole);if(owners)owners.classList.toggle('hidden',!ownerRole);if(audit)audit.classList.toggle('hidden',!isAdmin);if(admin&&!isAdmin)admin.classList.add('hidden');
    const {count:unread}=await opsClient.from('notifications').select('id',{head:true,count:'exact'}).is('read_at',null);const notif=document.querySelector('#notificationsNav');if(notif&&(unread||0)>0){const i=document.createElement('i');i.className='nav-badges';i.innerHTML=`<span class="nav-count yellow">${Math.min(unread,99)}</span>`;notif.appendChild(i)}
    const detail=document.querySelector('#participantDetail');if(detail){const observer=new MutationObserver(()=>queueMicrotask(enhanceParticipantDetail));observer.observe(detail,{childList:true,subtree:false});await enhanceParticipantDetail()}
  }catch(e){console.warn('[AidMe VIDA ops UI]',e)}
}
async function enhanceParticipantDetail(){
  if(opsBusy||!opsClient)return;const card=document.querySelector('.participant-card.active'),detail=document.querySelector('#participantDetail');if(!card||!detail)return;const participantId=card.dataset.participantId;if(!participantId||lastEnhancedParticipant===participantId&&detail.querySelector('#workflowGateCard'))return;opsBusy=true;
  try{
    const {data:p,error}=await opsClient.from('participants').select('id,stage').eq('id',participantId).maybeSingle();if(error||!p)return;const {data:{session}}=await opsClient.auth.getSession();if(!session)return;const {data:grants}=await opsClient.from('role_grants').select('role_code,revoked_at,valid_until').eq('user_id',session.user.id);const staff=(grants||[]).some(g=>!g.revoked_at&&(!g.valid_until||new Date(g.valid_until)>new Date()));if(!staff)return;
    let action='',label='',hint='',formKey='';if(p.stage==='VIA'||p.stage==='READY_FOR_GO'){formKey='individual_go_no_go';label='Åpne individuell GO / NO-GO';hint='Formell beslutning tas i det versjonerte VÍA-skjemaet.'}else if(['GO','GO_WITH_CONDITIONS'].includes(p.stage)){action='START_SER';label='Start SER';hint='Krever samlet Pilot-GO, navngitt VIDA-eier og lukkede vilkår.'}else if(p.stage==='SER'){action='START_VIDA';label='Overfør til VIDA';hint='Oppretter 72t/14d/30d/90d oppfølging med navngitt VIDA-eier.'}else if(p.stage==='VIDA'){action='START_NEW_VIA';label='Start ny VÍA';hint='Åpner neste veivalg uten å gjøre det automatisk.'}else{lastEnhancedParticipant=participantId;return}
    detail.querySelector('#workflowGateCard')?.remove();const box=document.createElement('div');box.id='workflowGateCard';box.className='panel-card';box.style.marginTop='14px';box.innerHTML=`<p class="eyebrow">Neste gate</p><h3>${label}</h3><p>${hint}</p><div class="form-actions"><a class="ghost" href="./owners.html?participant=${encodeURIComponent(participantId)}">Ansvar / eiere</a>${formKey?`<a class="primary" href="./form-runner.html?key=${encodeURIComponent(formKey)}&participant=${encodeURIComponent(participantId)}">${label}</a>`:`<button id="workflowGateButton" class="primary" type="button">${label}</button>`}</div><p id="workflowGateMessage" class="message"></p>`;detail.appendChild(box);lastEnhancedParticipant=participantId;
    const btn=box.querySelector('#workflowGateButton');if(btn)btn.addEventListener('click',async()=>{btn.disabled=true;const msg=box.querySelector('#workflowGateMessage');msg.textContent='Kontrollerer gate…';const {data,error}=await opsClient.functions.invoke('workflow-command',{body:{action,participantId}});if(error||data?.error){const map={PILOT_GO_REQUIRED:'Samlet Pilot-GO mangler eller er ikke GO.',NAMED_VIDA_OWNER_REQUIRED:'Navngitt VIDA-eier mangler.',GO_CONDITIONS_OPEN:'GO-vilkår må lukkes først.',SER_REQUIRES_INDIVIDUAL_GO:'Individuell GO mangler.',FORBIDDEN:'Rollen din har ikke myndighet til denne overgangen.'};msg.textContent=map[data?.error]||'Overgangen kunne ikke gjennomføres ennå. Ingen data ble endret.';btn.disabled=false;return}msg.textContent='Overgang registrert.';lastEnhancedParticipant=null;setTimeout(()=>location.reload(),500)})
  }finally{opsBusy=false}
}
async function boot(){
  const watchdog=setTimeout(()=>{const l=document.querySelector('#loading');if(l&&!l.classList.contains('hidden'))showFailure('Oppstart tar for lang tid. Last siden på nytt; ingen data er endret.')},12000);
  try{
    await ensureSupabase();
    const res=await fetch('./app-core-broken.js?v=20260817i',{cache:'no-store'});if(!res.ok)throw new Error('Portalkjerne mangler');let code=await res.text();
    if(!code.includes(BAD_SORT))throw new Error('Forventet oppstartsreparasjon ble ikke funnet');code=code.replace(BAD_SORT,GOOD_SORT);
    if(!code.includes(BAD_TASK))throw new Error('Forventet oppgavefunksjon ble ikke funnet');code=code.replace(BAD_TASK,GOOD_TASK);
    if(!code.includes(BAD_FORMS))throw new Error('Forventet skjemafunksjon ble ikke funnet');code=code.replace(BAD_FORMS,GOOD_FORMS);
    (0,eval)(`${code}\n//# sourceURL=aidme-portal-core-hotfixed.js`);
    setTimeout(installOpsUi,50);
  }catch(e){clearTimeout(watchdog);showFailure(`Portalen kunne ikke starte (${e.message}).`)}
}
window.addEventListener('error',e=>{const l=document.querySelector('#loading');if(l&&!l.classList.contains('hidden'))showFailure(`Oppstartsfeil: ${e.message||'ukjent feil'}.`)});
boot();
})();
