const SUPABASE_URL='https://ibloovohuhrceivrvhvn.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_JtNmgzTLlepPhKDCVsn6CA_Vk7BCClv';
const client=supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s);
let session=null,participants=[],pilots=[],pilotParticipants=[],grants=[],definitions=[],versions=[],currentDef=null,currentVersion=null,currentDraft=null;
const ROLE_KEYS={
 project_owner:['info_before_via','interest_referral','via_roadmap','participant_agreement','pilot_go','pilot_evaluation'],
 program_lead:['interest_referral','pilot_go'],
 via_owner:['info_before_via','interest_referral','via_roadmap','individual_go_no_go','participant_agreement'],
 clinical_professional:['info_before_via','interest_referral','via_roadmap','individual_go_no_go','participant_agreement'],
 ser_lead:['ser_daily','incident'],vida_owner:['vida_plan'],logistics:['pilot_go']
};
const PARTICIPANT_KEYS=['info_before_via','via_roadmap','participant_agreement','vida_plan'];
const PILOT_LEVEL_KEYS=new Set(['pilot_go','pilot_evaluation']);
const PARTICIPANT_REQUIRED_KEYS=new Set(['info_before_via','interest_referral','via_roadmap','individual_go_no_go','participant_agreement','ser_daily','vida_plan']);
function esc(v=''){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function active(g){const n=new Date();return !g.revoked_at&&(!g.valid_from||new Date(g.valid_from)<=n)&&(!g.valid_until||new Date(g.valid_until)>n)}
function ownParticipant(){return participants.find(p=>p.user_id===session?.user?.id)||null}
function isStaff(){return grants.some(active)}
function participantAllowedKeys(){
 const stage=String(ownParticipant()?.stage||'').toUpperCase();
 if(stage==='GO'||stage==='GO_WITH_CONDITIONS')return new Set(['participant_agreement']);
 if(stage==='POSTPONED'||stage==='NO_GO'||stage==='SER')return new Set();
 if(stage==='VIDA')return new Set(['vida_plan']);
 if(stage==='NEW_VIA')return new Set(['via_roadmap']);
 return new Set(['info_before_via','via_roadmap']);
}
function allowedKeys(){if(!isStaff())return participantAllowedKeys();const s=new Set();grants.filter(active).forEach(g=>(ROLE_KEYS[g.role_code]||[]).forEach(k=>s.add(k)));return s}
function selectedParticipant(){return participants.find(p=>p.id===$('#participantSelect').value)||null}
function explicitPilot(){return pilots.find(p=>p.id===$('#pilotSelect').value)||null}
function participantPilot(participantId){const link=pilotParticipants.find(x=>x.participant_id===participantId&&x.status==='ACTIVE');return link?pilots.find(p=>p.id===link.pilot_id)||null:null}
function selectedPilot(){return explicitPilot()||participantPilot(selectedParticipant()?.id)||null}
function orgId(){return selectedParticipant()?.organization_id||selectedPilot()?.organization_id||grants.find(active)?.organization_id||null}
function formVersionFor(defId){return versions.filter(v=>v.form_definition_id===defId&&!v.retired_at&&v.published_at).sort((a,b)=>b.version-a.version)[0]||null}
function phaseLabel(v){return String(v?.schema_json?.phase||'VÍA').replace('_',' → ')}

async function init(){
 const {data:{session:s}}=await client.auth.getSession();session=s;if(!session){location.replace('./');return}
 const aal=await client.auth.mfa.getAuthenticatorAssuranceLevel();const aal2=aal.data?.currentLevel==='aal2';$('#securityPill').textContent=aal2?'AAL2 · bekreftet':'AAL1 · utilstrekkelig';$('#securityPill').classList.toggle('secure',aal2);$('#securityPill').classList.toggle('attention',!aal2);if(!aal2){$('#blocked').classList.remove('hidden');$('#blockedText').textContent='Versjonerte programskjema krever at denne innloggingen er bekreftet med Authenticator.';return}
 const uid=session.user.id;const [pRes,gRes,dRes,vRes,pilotRes,ppRes]=await Promise.all([
  client.from('participants').select('id,organization_id,code_name,stage,user_id,active').eq('active',true),
  client.from('role_grants').select('id,organization_id,role_code,participant_id,pilot_id,valid_from,valid_until,revoked_at').eq('user_id',uid),
  client.from('form_definitions').select('id,key,title_no,scope').order('created_at'),
  client.from('form_versions').select('id,form_definition_id,version,schema_json,published_at,retired_at').order('version',{ascending:false}),
  client.from('pilots').select('id,organization_id,name,status,route_name,start_date,end_date').order('start_date',{ascending:false}),
  client.from('pilot_participants').select('pilot_id,participant_id,status')
 ]);participants=pRes.data||[];grants=gRes.data||[];definitions=dRes.data||[];versions=vRes.data||[];pilots=pilotRes.data||[];pilotParticipants=ppRes.data||[];
 $('#runner').classList.remove('hidden');fillParticipants();fillPilots();fillForms();applyQuery();syncPilotFromParticipant();await chooseForm();
}
function fillParticipants(){const own=ownParticipant(),staff=isStaff(),list=staff?participants:(own?[own]:[]);$('#participantSelect').innerHTML=(staff?'<option value="">Ingen enkelt deltaker / pilotnivå</option>':'')+list.map(p=>`<option value="${p.id}">${esc(p.code_name)} · ${esc(p.stage)}</option>`).join('')}
function fillPilots(){const visible=isStaff()?pilots:pilots.filter(p=>pilotParticipants.some(x=>x.pilot_id===p.id&&x.participant_id===ownParticipant()?.id));$('#pilotSelect').innerHTML='<option value="">Avledes fra deltaker / ikke valgt</option>'+visible.map(p=>`<option value="${p.id}">${esc(p.name)}${p.route_name?` · ${esc(p.route_name)}`:''}</option>`).join('')}
function fillForms(){const keys=allowedKeys(),defs=definitions.filter(d=>keys.has(d.key)&&formVersionFor(d.id));$('#formSelect').innerHTML=defs.map(d=>`<option value="${d.id}">${esc(d.title_no)}</option>`).join('')}
function applyQuery(){const q=new URLSearchParams(location.search),key=q.get('key'),participant=q.get('participant'),pilot=q.get('pilot');if(key){const d=definitions.find(x=>x.key===key);if(d&&[...$('#formSelect').options].some(o=>o.value===d.id))$('#formSelect').value=d.id}if(participant&&[...$('#participantSelect').options].some(o=>o.value===participant))$('#participantSelect').value=participant;if(pilot&&[...$('#pilotSelect').options].some(o=>o.value===pilot))$('#pilotSelect').value=pilot}
function syncPilotFromParticipant(){if($('#pilotSelect').value)return;const pp=participantPilot($('#participantSelect').value);if(pp&&[...$('#pilotSelect').options].some(o=>o.value===pp.id))$('#pilotSelect').value=pp.id}
function contextOk(){if(!currentDef)return false;const participant=selectedParticipant(),pilot=selectedPilot();if(PARTICIPANT_REQUIRED_KEYS.has(currentDef.key)&&!participant){$('#contextNote').textContent='Velg en deltaker før dette skjemaet kan lagres.';$('#contextNote').classList.remove('hidden');return false}if(PILOT_LEVEL_KEYS.has(currentDef.key)&&!pilot){$('#contextNote').textContent='Velg pilot / gruppe før dette pilotskjemaet kan lagres.';$('#contextNote').classList.remove('hidden');return false}$('#contextNote').classList.add('hidden');return true}
async function chooseForm(){currentDef=definitions.find(d=>d.id===$('#formSelect').value)||null;currentVersion=currentDef?formVersionFor(currentDef.id):null;currentDraft=null;if(!currentDef||!currentVersion){$('#formTitle').textContent='Ingen tilgjengelig mal';$('#formSections').innerHTML='';return}$('#formTitle').textContent=currentDef.title_no;$('#versionLabel').textContent=`v${currentVersion.version}`;$('#phaseLabel').textContent=phaseLabel(currentVersion);$('#scopeLabel').textContent=currentDef.scope;$('#formIntro').textContent=currentVersion.schema_json?.intro||'';renderSections();contextOk();await loadSubmissions()}
function renderSections(){const sections=currentVersion.schema_json?.sections||[];$('#formSections').innerHTML=sections.map((sec,si)=>`<section class="form-section"><h3>${esc(sec.title||`Del ${si+1}`)}</h3><div class="dynamic-grid">${(sec.fields||[]).map(renderField).join('')}</div></section>`).join('')}
function renderField(f){const required=f.required?' required':'',full=['textarea','action','multi_select'].includes(f.type)?' full':'';let input='';if(f.type==='textarea')input=`<textarea name="${esc(f.key)}" rows="4"${required}></textarea>`;else if(f.type==='select')input=`<select name="${esc(f.key)}"${required}><option value="">Velg</option>${(f.options||[]).map(o=>`<option value="${esc(o)}">${esc(String(o).replaceAll('_',' '))}</option>`).join('')}</select>`;else if(f.type==='tri_state')input=`<div class="tri-state">${[['YES','Ja'],['NO','Nei'],['UNRESOLVED','Ikke avklart']].map(([v,l])=>`<label><input type="radio" name="${esc(f.key)}" value="${v}"${required}> ${l}</label>`).join('')}</div>`;else if(f.type==='checkbox')input=`<label class="check-row"><input type="checkbox" name="${esc(f.key)}"> Bekreft</label>`;else if(f.type==='range')input=`<input type="range" name="${esc(f.key)}" min="${f.min??0}" max="${f.max??10}" value="5"><small data-range-for="${esc(f.key)}">5</small>`;else if(f.type==='datetime')input=`<input type="datetime-local" name="${esc(f.key)}"${required}>`;else if(f.type==='multi_select')input=`<div class="multi-select">${(f.options||[]).map(o=>`<label><input type="checkbox" name="${esc(f.key)}" value="${esc(o)}"> ${esc(String(o).replaceAll('_',' '))}</label>`).join('')}</div>`;else if(f.type==='action')input=`<div class="action-fields"><input name="${esc(f.key)}__action" placeholder="Konkret handling"${required}><input name="${esc(f.key)}__support" placeholder="Støtte/eier"><input name="${esc(f.key)}__deadline" type="date"></div>`;else input=`<input type="text" name="${esc(f.key)}"${required}>`;return `<div class="field-wrap${full}"><label><span>${esc(f.label)}${f.required?' *':''}</span>${input}${f.help?`<small>${esc(f.help)}</small>`:''}</label></div>`}
function bindRanges(){document.querySelectorAll('input[type="range"]').forEach(el=>el.addEventListener('input',()=>{const out=document.querySelector(`[data-range-for="${CSS.escape(el.name)}"]`);if(out)out.textContent=el.value}))}
function payloadFromForm(){const fd=new FormData($('#dynamicForm')),out={};for(const sec of currentVersion.schema_json?.sections||[])for(const f of sec.fields||[]){if(f.type==='checkbox')out[f.key]=$(`[name="${CSS.escape(f.key)}"]`)?.checked||false;else if(f.type==='multi_select')out[f.key]=fd.getAll(f.key);else if(f.type==='action')out[f.key]={action:fd.get(`${f.key}__action`)||'',support:fd.get(`${f.key}__support`)||'',deadline:fd.get(`${f.key}__deadline`)||null};else out[f.key]=fd.get(f.key)??null}return out}
function restorePayload(payload={}){for(const sec of currentVersion?.schema_json?.sections||[])for(const f of sec.fields||[]){const value=payload?.[f.key];if(value==null)continue;if(f.type==='checkbox'){const el=$(`[name="${CSS.escape(f.key)}"]`);if(el)el.checked=!!value}else if(f.type==='multi_select'){document.querySelectorAll(`[name="${CSS.escape(f.key)}"]`).forEach(el=>el.checked=Array.isArray(value)&&value.includes(el.value))}else if(f.type==='tri_state'){const el=document.querySelector(`[name="${CSS.escape(f.key)}"][value="${CSS.escape(String(value))}"]`);if(el)el.checked=true}else if(f.type==='action'){const a=$(`[name="${CSS.escape(f.key+'__action')}"]`),s=$(`[name="${CSS.escape(f.key+'__support')}"]`),d=$(`[name="${CSS.escape(f.key+'__deadline')}"]`);if(a)a.value=value.action||'';if(s)s.value=value.support||'';if(d)d.value=value.deadline||''}else{const el=$(`[name="${CSS.escape(f.key)}"]`);if(el)el.value=value;if(f.type==='range'){const out=document.querySelector(`[data-range-for="${CSS.escape(f.key)}"]`);if(out)out.textContent=value}}}}
async function save(status){if(!currentVersion||!contextOk())return;const participant=selectedParticipant(),pilot=selectedPilot(),org=orgId();if(!org){$('#formMessage').textContent='Mangler organisasjonskontekst.';return}if(status==='SUBMITTED'&&!$('#dynamicForm').reportValidity())return;const row={organization_id:org,participant_id:participant?.id||null,pilot_id:pilot?.id||null,form_version_id:currentVersion.id,submitted_by:session.user.id,status,payload:payloadFromForm(),updated_at:new Date().toISOString(),submitted_at:status==='SUBMITTED'?new Date().toISOString():null};$('#formMessage').textContent='Lagrer…';let res;if(currentDraft?.id)res=await client.from('form_submissions').update(row).eq('id',currentDraft.id).select('id,status').single();else res=await client.from('form_submissions').insert(row).select('id,status').single();if(res.error){$('#formMessage').textContent=`Kunne ikke lagre: ${res.error.message}`;return}$('#formMessage').textContent=status==='SUBMITTED'?'Skjema fullført. Versjon, deltaker og pilotkontekst er bevart.':'Utkast lagret – du kan fortsette senere.';if(status==='DRAFT')currentDraft={id:res.data.id};else currentDraft=null;await loadSubmissions()}
async function loadSubmissions(){if(!currentVersion)return;const participantId=$('#participantSelect').value||null,pilotId=selectedPilot()?.id||null;let q=client.from('form_submissions').select('id,participant_id,pilot_id,form_version_id,submitted_by,status,submitted_at,created_at,updated_at,payload').eq('form_version_id',currentVersion.id).order('created_at',{ascending:false}).limit(20);q=participantId?q.eq('participant_id',participantId):q.is('participant_id',null);q=pilotId?q.eq('pilot_id',pilotId):q.is('pilot_id',null);const {data,error}=await q;if(error){$('#submissionList').innerHTML='<p>Ingen tilgjengelig historikk.</p>';return}const rows=data||[];currentDraft=rows.find(r=>r.status==='DRAFT'&&r.submitted_by===session.user.id)||null;$('#submissionList').innerHTML=rows.length?rows.map(r=>`<div class="submission-row"><div><b>${r.status==='SUBMITTED'?'Fullført':'Utkast'}</b><small>${new Intl.DateTimeFormat('nb-NO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(r.submitted_at||r.updated_at||r.created_at))}</small></div><span class="pill">v${currentVersion.version}</span></div>`).join(''):'<p>Ingen registreringer for denne konteksten ennå.</p>';if(currentDraft){restorePayload(currentDraft.payload||{});$('#formMessage').textContent='Eget tidligere utkast er hentet inn.'}bindRanges()}
$('#formSelect').addEventListener('change',chooseForm);$('#participantSelect').addEventListener('change',()=>{syncPilotFromParticipant();chooseForm()});$('#pilotSelect').addEventListener('change',chooseForm);$('#saveDraft').addEventListener('click',()=>save('DRAFT'));$('#dynamicForm').addEventListener('submit',e=>{e.preventDefault();save('SUBMITTED')});client.auth.onAuthStateChange(()=>setTimeout(init,0));init();