const SUPABASE_URL='https://ibloovohuhrceivrvhvn.supabase.co';
const SUPABASE_KEY='sb_publishable_JtNmgzTLlepPhKDCVsn6CA_Vk7BCClv';
const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=s=>document.querySelector(s);let session=null,aal2=false;
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(v){return new Intl.DateTimeFormat('nb-NO',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
function safeName(name){return String(name||'fil').normalize('NFKD').replace(/[^A-Za-z0-9._-]+/g,'-').slice(-120)||'fil'}
async function loadNotifications(){const {data,error}=await client.from('notifications').select('id,task_id,kind,title,safe_preview,read_at,created_at').order('created_at',{ascending:false}).limit(100);if(error){$('#notifications').innerHTML='<p>Varsler kunne ikke lastes.</p>';return}const rows=data||[],unread=rows.filter(x=>!x.read_at),critical=unread.filter(x=>String(x.kind).toUpperCase()==='SOS');$('#notificationHeading').textContent=`${unread.length} ulest${critical.length?` · ${critical.length} kritisk`:''}`;const ordered=[...rows].sort((a,b)=>(String(b.kind).toUpperCase()==='SOS'?1:0)-(String(a.kind).toUpperCase()==='SOS'?1:0)||String(b.created_at).localeCompare(String(a.created_at)));$('#notifications').innerHTML=ordered.length?ordered.map(n=>`<div class="inbox-item ${!n.read_at?'inbox-unread':''} ${String(n.kind).toUpperCase()==='SOS'?'inbox-critical':''}"><div><b>${esc(n.title)}</b><small>${esc(n.safe_preview||'Åpne AidMe VIDA for detaljer.')} · ${esc(fmt(n.created_at))}</small></div>${n.read_at?'':'<button class="ghost compact" data-read="'+esc(n.id)+'">Marker lest</button>'}</div>`).join(''):'<p>Ingen varsler.</p>';document.querySelectorAll('[data-read]').forEach(b=>b.addEventListener('click',async()=>{await client.from('notifications').update({read_at:new Date().toISOString()}).eq('id',b.dataset.read);await loadNotifications()}))}
async function loadFiles(){const {data,error}=await client.from('personal_documents').select('id,title,storage_path,mime_type,category,sensitivity,created_at').order('created_at',{ascending:false});if(error){$('#files').innerHTML='<p>Filer kunne ikke lastes.</p>';return}$('#files').innerHTML=(data||[]).length?(data||[]).map(d=>`<div class="file-row"><div><b>${esc(d.title)}</b><small>${esc(d.mime_type||d.category||'Fil')} · ${esc(fmt(d.created_at))}</small></div><button class="ghost compact" data-open="${esc(d.storage_path||'')}">Åpne</button></div>`).join(''):'<p>Ingen filer i innboksen ennå.</p>';document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',async()=>{const path=b.dataset.open;if(!path)return;const {data,error}=await client.storage.from('personal-documents').createSignedUrl(path,60);if(error||!data?.signedUrl){$('#fileMessage').textContent='Filen kunne ikke åpnes med din tilgang.';return}location.href=data.signedUrl}))}
async function upload(){const f=$('#file').files?.[0];if(!f){$('#fileMessage').textContent='Velg en fil først.';return}if(!aal2){$('#fileMessage').textContent='Bekreft Authenticator (AAL2) i portalen før opplasting.';return}if(f.size>25*1024*1024){$('#fileMessage').textContent='Filen er større enn 25 MB.';return}const path=`${session.user.id}/${crypto.randomUUID()}-${safeName(f.name)}`;$('#fileMessage').textContent='Laster opp…';const up=await client.storage.from('personal-documents').upload(path,f,{upsert:false,contentType:f.type||undefined});if(up.error){$('#fileMessage').textContent='Opplasting feilet.';return}const meta=await client.from('personal_documents').insert({owner_user_id:session.user.id,participant_id:null,category:'INBOX',title:f.name,storage_path:path,mime_type:f.type||'application/octet-stream',sensitivity:'INTERNAL'}).select('id').single();if(meta.error){await client.storage.from('personal-documents').remove([path]);$('#fileMessage').textContent='Filen ble ikke registrert og er ryddet bort.';return}$('#file').value='';$('#fileMessage').textContent='Filen er lagret privat i innboksen.';await loadFiles()}
async function init(){const {data}=await client.auth.getSession();session=data.session;if(!session){location.replace('./');return}const a=await client.auth.mfa.getAuthenticatorAssuranceLevel();aal2=a.data?.currentLevel==='aal2';$('#status').textContent=aal2?'AAL2 bekreftet · privat innboks':'Varsler kan leses. Filopplasting krever AAL2.';await Promise.all([loadNotifications(),loadFiles()])}
$('#refresh').addEventListener('click',()=>Promise.all([loadNotifications(),loadFiles()]));$('#upload').addEventListener('click',upload);init();