const SUPABASE_URL='https://ibloovohuhrceivrvhvn.supabase.co';const SUPABASE_KEY='sb_publishable_JtNmgzTLlepPhKDCVsn6CA_Vk7BCClv';const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=s=>document.querySelector(s);let pilots=[],participants=[],links=[],routeDays=[],checkins=[],tasks=[];
function esc(v=''){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function latestFor(pid){return checkins.filter(c=>c.participant_id===pid).sort((a,b)=>String(b.checkin_date).localeCompare(String(a.checkin_date)))[0]||null}
function openTaskFor(pid){return tasks.filter(t=>t.participant_id===pid&&['OPEN','IN_PROGRESS','WAITING'].includes(t.status)).sort((a,b)=>new Date(a.due_at||'2999')-new Date(b.due_at||'2999'))[0]||null}
function ragLabel(r){return r==='RED'?'Rød':r==='YELLOW'?'Gul':'Grønn'}function taskAttention(t){return t&&(t.severity==='RED'||(t.due_at&&new Date(t.due_at)<new Date()))?'RED':t?.severity||'GREEN'}
async function init(){const {data:{session}}=await client.auth.getSession();if(!session){location.replace('./');return}const aal=await client.auth.mfa.getAuthenticatorAssuranceLevel(),ok=aal.data?.currentLevel==='aal2';$('#securityPill').textContent=ok?'AAL2 · bekreftet':'AAL1 · utilstrekkelig';$('#securityPill').classList.toggle('secure',ok);if(!ok){$('#blocked').classList.remove('hidden');return}await load();if(!pilots.length){$('#blocked').classList.remove('hidden');$('#blockedText').textContent='Ingen pilot er tilgjengelig for denne rollen/scope.';return}$('#work').classList.remove('hidden');fillPilots();selectPilot()}
async function load(){const [p,pp,r,parts,c,t]=await Promise.all([client.from('pilots').select('id,name,status,start_date,end_date,route_name,route_variant,start_location,end_location').order('start_date'),client.from('pilot_participants').select('pilot_id,participant_id,status,joined_at'),client.from('pilot_route_days').select('id,pilot_id,day_number,route_date,from_place,to_place,distance_km,route_rag,note').order('day_number'),client.from('participants').select('id,code_name,stage,active').eq('active',true),client.from('ser_checkins').select('id,participant_id,checkin_date,mood,stress,energy,sleep,belonging,agency,direction,rag,participant_note').order('checkin_date'),client.from('tasks').select('id,participant_id,pilot_id,title,description,status,due_at,severity,priority,task_type,workflow_key').in('status',['OPEN','IN_PROGRESS','WAITING']).order('due_at',{ascending:true,nullsFirst:false})]);pilots=p.data||[];links=pp.data||[];routeDays=r.data||[];participants=parts.data||[];checkins=c.data||[];tasks=t.data||[]}
function fillPilots(){const previous=$('#pilotSelect').value;$('#pilotSelect').innerHTML=pilots.map(p=>`<option value="${p.id}">${esc(p.name)}${p.route_name?` · ${esc(p.route_name)}`:''}</option>`).join('');if(previous&&pilots.some(p=>p.id===previous))$('#pilotSelect').value=previous}
function daysFor(pilotId){return routeDays.filter(d=>d.pilot_id===pilotId).sort((a,b)=>(a.day_number||0)-(b.day_number||0))}
function defaultDay(days){if(!days.length)return null;const today=new Date().toISOString().slice(0,10);return days.find(d=>d.route_date===today)||days.find(d=>d.route_date&&d.route_date>today)||days[days.length-1]}
function selectPilot(){const pilot=pilots.find(p=>p.id===$('#pilotSelect').value)||pilots[0];if(!pilot)return;$('#pilotSelect').value=pilot.id;$('#pilotStatus').textContent=pilot.status||'–';const days=daysFor(pilot.id),previous=$('#daySelect').value;$('#daySelect').innerHTML=days.map(d=>`<option value="${d.id}">Dag ${d.day_number}${d.route_date?` · ${d.route_date}`:''} · ${esc(d.from_place||'')} → ${esc(d.to_place||'')}</option>`).join('');const def=days.some(d=>d.id===previous)?days.find(d=>d.id===previous):defaultDay(days);if(def)$('#daySelect').value=def.id;$('#pilotGoLink').href=`./form-runner.html?key=pilot_go&pilot=${encodeURIComponent(pilot.id)}`;render()}
function render(){const pilot=pilots.find(p=>p.id===$('#pilotSelect').value);if(!pilot)return;const day=routeDays.find(d=>d.id===$('#daySelect').value)||defaultDay(daysFor(pilot.id));$('#dayEyebrow').textContent=day?`Dag ${day.day_number}${day.route_date?` · ${day.route_date}`:''}`:'Rute';$('#routeTitle').textContent=day?`${day.from_place||'–'} → ${day.to_place||'–'}`:(pilot.route_name||'Rute ikke registrert');$('#routeMeta').textContent=day?`${day.distance_km??'–'} km${day.note?` · ${day.note}`:''}`:[pilot.start_location,pilot.end_location].filter(Boolean).join(' → ');$('#routeRag').textContent=day?.route_rag?ragLabel(day.route_rag):'–';const ids=links.filter(x=>x.pilot_id===pilot.id&&x.status==='ACTIVE').map(x=>x.participant_id),list=participants.filter(p=>ids.includes(p.id));$('#participantCount').textContent=list.length;let g=0,y=0,r=0;list.forEach(p=>{const c=latestFor(p.id),rag=c?.rag||'GREEN';if(rag==='RED')r++;else if(rag==='YELLOW')y++;else g++});$('#greenCount').textContent=g;$('#yellowCount').textContent=y;$('#redCount').textContent=r;const pilotTasks=tasks.filter(t=>t.pilot_id===pilot.id);$('#taskCount').textContent=pilotTasks.length;$('#participantList').innerHTML=list.length?list.map(p=>participantCard(p,pilot.id)).join(''):'<p>Ingen aktive deltakere i piloten.</p>';$('#taskList').innerHTML=pilotTasks.length?pilotTasks.map(taskRow).join(''):'<p>Ingen åpne operative oppgaver for denne rollen.</p>';document.querySelectorAll('[data-task-id]').forEach(b=>b.addEventListener('click',()=>location.href='./#tasks'))}
function participantCard(p,pilotId){const c=latestFor(p.id),rag=c?.rag||'GREEN',t=openTaskFor(p.id),attention=taskAttention(t);return `<article class="participant-card"><i class="status-dot ${rag}"></i><div><b>${esc(p.code_name)}</b><small>${esc(p.stage)} · siste innsjekk ${esc(c?.checkin_date||'–')}${c?` · stress ${c.stress??'–'} · energi ${c.energy??'–'}`:''}</small><div class="form-actions" style="justify-content:flex-start;margin-top:8px"><a class="ghost compact" href="./form-runner.html?key=ser_daily&participant=${encodeURIComponent(p.id)}&pilot=${encodeURIComponent(pilotId)}">SER-logg</a><a class="ghost compact" href="./form-runner.html?key=incident&participant=${encodeURIComponent(p.id)}&pilot=${encodeURIComponent(pilotId)}">Avvik</a></div></div><div class="task-meta"><span class="pill ${rag}">${ragLabel(rag)}</span>${t?`<span class="pill ${attention}">${attention==='RED'?'Oppgave krever handling':'Oppgave'}</span>`:''}</div></article>`}
function taskRow(t){const attention=taskAttention(t),overdue=t.due_at&&new Date(t.due_at)<new Date();return `<button class="task-row" data-task-id="${t.id}"><i class="task-dot ${attention}"></i><div><b>${esc(t.title)}</b><small>${esc(t.description||t.task_type||'')}</small></div><div class="task-meta"><span class="pill ${attention}">${overdue?'Forfalt':attention==='RED'?'Kritisk':attention==='YELLOW'?'Avklar':'Normal'}</span></div></button>`}
$('#pilotSelect').addEventListener('change',selectPilot);$('#daySelect').addEventListener('change',render);$('#refresh').addEventListener('click',async()=>{await load();fillPilots();selectPilot()});client.auth.onAuthStateChange(()=>setTimeout(init,0));init();