import fs from 'node:fs';
import vm from 'node:vm';

const app=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');
const onboarding=fs.readFileSync(new URL('./onboarding.js',import.meta.url),'utf8');
const onboardingHtml=fs.readFileSync(new URL('./onboarding.html',import.meta.url),'utf8');
const formHtml=fs.readFileSync(new URL('./form-runner.html',import.meta.url),'utf8');
const formA11y=fs.readFileSync(new URL('./form-accessibility.js',import.meta.url),'utf8');
const formCapture=fs.readFileSync(new URL('./form-auth-return-capture.js',import.meta.url),'utf8');
const formGuard=fs.readFileSync(new URL('./form-runner-guard.js',import.meta.url),'utf8');
const appAuthReturn=fs.readFileSync(new URL('./app-auth-return.js',import.meta.url),'utf8');
const redirects=fs.readFileSync(new URL('../_redirects',import.meta.url),'utf8');
if(redirects.includes('/portal/app.js /portal/app-hotfix.js'))throw new Error('Emergency app redirect must not be present in clean-build mode.');
if(!app.includes("client.functions.invoke('task-command'"))throw new Error('Built app is missing the secure task command path.');
if(!app.includes('Forfalt ·'))throw new Error('Built app is missing overdue-task presentation.');
if(!app.includes('Operational extensions are maintained separately'))throw new Error('Operational extension module was not concatenated.');
if(!app.includes('UX/auth/mobile hardening is maintained separately'))throw new Error('UX hardening extension module was not concatenated.');
if(!app.includes('Role onboarding navigation is maintained separately'))throw new Error('Role onboarding navigation module was not concatenated.');
if(!app.includes('resetPasswordForEmail'))throw new Error('Built app is missing password recovery.');
if(!app.includes("o.value='7'"))throw new Error('Built app is missing 7-day analysis option.');
if(!app.includes('mobileAttentionBar'))throw new Error('Built app is missing mobile attention summary.');
if(!app.includes('task-crosslinks'))throw new Error('Built app is missing contextual task drill-down.');
if(!app.includes('role_onboarding_items'))throw new Error('Built app is missing onboarding alert integration.');
if(!onboarding.includes("functions.invoke('onboarding-command'"))throw new Error('Onboarding page is missing secure onboarding command path.');
if(!onboardingHtml.includes('Din rolleintroduksjon'))throw new Error('Onboarding page shell is missing.');
if(app.includes('app-core-broken.js?v='))throw new Error('Built app still contains emergency runtime loader logic.');
if(!app.includes('aidme:return-intent:v1')||!app.includes('Fortsett der du slapp.'))throw new Error('Built app is missing protected auth return context.');
if(!formHtml.includes('form-auth-return-capture.js')||formHtml.indexOf('form-auth-return-capture.js')>formHtml.indexOf('form-runner.js'))throw new Error('Form return intent must be captured before form-runner auth redirect can run.');
if(!formHtml.includes('form-accessibility.js')||formHtml.indexOf('form-accessibility.js')<formHtml.indexOf('form-runner.js'))throw new Error('Accessible form renderer must load after the base renderer.');
if(!formA11y.includes('<fieldset class="field-group">')||!formA11y.includes('<legend>')||!formA11y.includes('aria-describedby')||!formA11y.includes('Støtte/eier')||!formA11y.includes('Frist'))throw new Error('Dynamic form accessibility layer is missing grouped semantics or action labels.');
if(!formA11y.includes('Obligatoriske felt er merket med *.')||!formGuard.includes("w.dataset.required==='true'")||!formGuard.includes("querySelector('legend')"))throw new Error('Required-field semantics must remain understandable and validated.');
if(!formCapture.includes('sessionStorage.setItem')||!appAuthReturn.includes("currentLevel==='aal2'")||!appAuthReturn.includes('location.replace(intent.target)'))throw new Error('Deep-link return must preserve intent and resume only after AAL2.');
if(appAuthReturn.includes('.from(')||appAuthReturn.includes('functions.invoke')||formCapture.includes('.from(')||formCapture.includes('functions.invoke')||formA11y.includes('.from(')||formA11y.includes('functions.invoke'))throw new Error('Return/accessibility layers must remain presentation/navigation-only.');
new vm.Script(app,{filename:'portal-app-built.js'});
new vm.Script(onboarding,{filename:'portal-onboarding.js'});
new vm.Script(formA11y,{filename:'portal-form-accessibility.js'});
new vm.Script(formCapture,{filename:'portal-form-auth-return-capture.js'});
new vm.Script(appAuthReturn,{filename:'portal-app-auth-return.js'});
console.log('Clean portal bundle compiles with secure tasks, auth recovery, protected return context, accessible forms, mobile UX, contextual drill-down and role onboarding.');
