(()=>{
'use strict';
let inboxChecked=false;
function activeRoles(){try{return [...new Set((accessGrants||[]).filter(activeGrant).map(g=>String(g.role_code||'')))]}catch{return[]}}
function profileTools(){return document.querySelector('#profileToolsSummary .profile-tool-links')}
function ensureExtraLinks(){const tools=profileTools();if(!tools)return;const labels=[...tools.querySelectorAll('a')].map(a=>(a.textContent||'').trim());if(!labels.some(x=>x.startsWith('Innboks'))){const a=document.createElement('a');a.className='ghost compact';a.href='./inbox.html';a.id='uatInboxLink';a.textContent='Innboks';tools.prepend(a)}if(activeRoles().includes('system_admin')&&!labels.includes('UAT full oversikt')){const a=document.createElement('a');a.className='ghost compact';a.href='./uat-overview.html';a.textContent='UAT full oversikt';a.title='Tidsbegrenset Early-UAT-visning. Ikke ordinær systemadministratortilgang.';tools.appendChild(a)}}
function fixManualTaskVisibility(){const allowed=activeRoles().some(r=>['program_lead','ser_lead'].includes(r));document.querySelectorAll('[data-manual-task]').forEach(b=>{if(!allowed)b.remove()})}
async function refreshInboxBadge(){if(inboxChecked||!client||!session)return;inboxChecked=true;try{const {data,error}=await client.from('notifications').select('id,kind,read_at').is('read_at',null).limit(100);if(error)return;const unread=(data||[]).length,critical=(data||[]).filter(n=>String(n.kind).toUpperCase()==='SOS').length;ensureExtraLinks();const link=document.querySelector('#uatInboxLink');if(link){link.innerHTML=`Innboks${unread?` <span class="nav-count ${critical?'red':'yellow'}" aria-label="${unread} uleste varsler">${unread}</span>`:''}`}
 if(critical){const view=document.querySelector('#view-overview');if(view&&!document.querySelector('#uatCriticalInbox')){const card=document.createElement('article');card.id='uatCriticalInbox';card.className='panel-card warning-card';card.innerHTML=`<p class="eyebrow">Kritisk varsel</p><h2>${critical} ulest${critical===1?'':'e'} beredskapsvarsel</h2><p>Åpne innboksen eller Hjelp & SOS. Ingen personopplysninger vises i varselteksten.</p><a class="primary" href="./inbox.html">Åpne innboks</a>`;view.insertAdjacentElement('afterbegin',card)}}}catch{}}
function apply(){ensureExtraLinks();fixManualTaskVisibility();refreshInboxBadge()}
const obs=new MutationObserver(()=>{clearTimeout(obs._t);obs._t=setTimeout(apply,35)});obs.observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('aidme:portal-rendered',()=>{inboxChecked=false;setTimeout(apply,0)});[0,180,600,1400].forEach(ms=>setTimeout(apply,ms));
})();