const SUPABASE_URL='https://ibloovohuhrceivrvhvn.supabase.co';
const SUPABASE_KEY='sb_publishable_JtNmgzTLlepPhKDCVsn6CA_Vk7BCClv';
const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);
const ROLE_NAMES={system_admin:'Systemadministrator',project_owner:'Prosjekteier',program_lead:'Programleder',via_owner:'VÍA-ansvarlig',clinical_professional:'Relevant fagperson',ser_lead:'SER-/turleder',vida_owner:'VIDA-eier',logistics:'Logistikk / beredskap',observer:'Observatør',evaluator:'Evaluator',break_glass:'Midlertidig nødtilgang'};
let state=null,factor=null;
function esc(v=''){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function show(title,text){const m=$('#message');m.classList.remove('hidden');m.innerHTML=`<h3>${esc(title)}</h3><p>${esc(text)}</p>`}
function hideMessage(){$('#message').classList.add('hidden')}
async function invoke(body){const {data,error}=await client.functions.invoke('account-setup-command',{body});if(error||data?.error)throw new Error(data?.error||error?.message||'REQUEST_FAILED');return data}
function fill(data){
  state=data;$('#setup').classList.remove('hidden');$('#sessionPill').textContent='Invitasjon · bekreftet';$('#sessionPill').classList.add('secure');$('#displayName').value=data.profile?.display_name||data.identity?.legal_name||data.staff?.full_name||'';$('#phone').value=data.identity?.phone||data.staff?.phone||'';$('#locale').value=data.profile?.locale||'nb';
  const participant=data.accountType==='participant';$('#participantFields').classList.toggle('hidden',!participant);$('#staffFields').classList.toggle('hidden',participant);$('#continueButton').classList.add('hidden');
  if(participant){
    $('#birthYear').value=data.identity?.birth_year||'';$('#preferredContact').value=data.identity?.preferred_contact_method||'EMAIL';$('#accountContext').innerHTML=`<strong>Deltaker · ${esc(data.participant?.code_name||'egen reise')}</strong><span>Fase: ${esc(data.participant?.stage||'VÍA')}</span>`;$('#profileHeading').textContent='Din deltakerprofil';$('#nextText').textContent='Etter grunnprofilen kan du åpne Min reise. Authenticator kan settes opp med én gang, men kreves først når du skal åpne beskyttede personlige skjema og sikkerhetssteg.';
  }else{
    $('#jobTitle').value=data.staff?.job_title||'';$('#accountContext').innerHTML=`<strong>Medarbeider / partner</strong><span>${esc(data.accountEmail||'')}</span>`;$('#profileHeading').textContent='Din arbeidsprofil';$('#roleList').innerHTML=(data.roles||[]).length?(data.roles||[]).map(r=>`<div class="role-chip"><b>${esc(ROLE_NAMES[r.role_code]||r.role_code)}</b><span>${r.participant_id?'Avgrenset deltaker':r.pilot_id?'Pilot':'Relevant arbeidsflate'}</span></div>`).join(''):'<div class="role-chip"><b>Tilgang venter</b><span>Administrator har ikke tildelt arbeidsrolle ennå.</span></div>';$('#nextText').textContent=(data.roles||[]).length?'Arbeidsrollen er tildelt. Før rolleintroduksjonen åpnes, beskytter vi arbeidsflaten med Authenticator.':'Profilen kan opprettes nå. Du får arbeidsflaten når administrator har tildelt riktig rolle og omfang.';
  }
  refreshMfa();
}
async function refreshMfa(){
  if(!state)return;const area=$('#mfaArea');area.classList.remove('hidden');const participant=state.accountType==='participant';const {data,error}=await client.auth.mfa.getAuthenticatorAssuranceLevel();
  if(error){area.innerHTML='<div class="mfa-box"><h3>Sikkerhetskontroll</h3><p>Kunne ikke lese tofaktorstatus. Prøv igjen før du går videre til beskyttede opplysninger.</p></div>';if(participant){$('#continueButton').href='./';$('#continueButton').textContent='Åpne Min reise';$('#continueButton').classList.remove('hidden')}return}
  if(data.currentLevel==='aal2'){
    area.innerHTML=participant?'<div class="mfa-box"><h3>✓ Sikker innlogging bekreftet</h3><p>Du kan åpne Min reise og de beskyttede skjemaene som gjelder fasen din.</p></div>':'<div class="mfa-box"><h3>✓ Tofaktor bekreftet</h3><p>Arbeidsflaten kan åpnes med rolle og omfang som administrator har tildelt.</p></div>';
    $('#continueButton').href=participant?'./':'./onboarding.html';$('#continueButton').textContent=participant?'Åpne Min reise':'Start rolleintroduksjon';$('#continueButton').classList.remove('hidden');return;
  }
  const factors=await client.auth.mfa.listFactors();const verified=factors.data?.totp?.find(x=>x.status==='verified');
  if(participant){
    $('#continueButton').href='./';$('#continueButton').textContent='Åpne Min reise';$('#continueButton').classList.remove('hidden');
    if(verified){factor={id:verified.id,existing:true};area.innerHTML='<div class="mfa-box"><h3>Sikre kontoen før beskyttede steg</h3><p>Du kan se Min reise nå. Når du skal åpne personlige skjema eller sikkerhetsopplysninger, må Authenticator bekreftes.</p><div class="mfa-row"><label><span>Kode</span><input id="mfaCode" inputmode="numeric" autocomplete="one-time-code" maxlength="6"></label><button id="verifyMfa" class="primary" type="button">Bekreft nå</button></div><p id="mfaMessage" class="message"></p></div>';$('#verifyMfa').addEventListener('click',verifyMfa);return}
    area.innerHTML='<div class="mfa-box"><h3>Ekstra sikkerhet</h3><p>Du kan åpne Min reise først og sette opp Authenticator når du kommer til et beskyttet personlig skjema. Du kan også gjøre det nå.</p><button id="startMfa" class="ghost" type="button">Sett opp Authenticator nå</button></div>';$('#startMfa').addEventListener('click',startMfa);return;
  }
  $('#continueButton').classList.add('hidden');
  if(verified){factor={id:verified.id,existing:true};area.innerHTML='<div class="mfa-box"><h3>Bekreft Authenticator</h3><p>Skriv inn den seks-sifrede koden før rolledata åpnes.</p><div class="mfa-row"><label><span>Kode</span><input id="mfaCode" inputmode="numeric" autocomplete="one-time-code" maxlength="6"></label><button id="verifyMfa" class="primary" type="button">Bekreft</button></div><p id="mfaMessage" class="message"></p></div>';$('#verifyMfa').addEventListener('click',verifyMfa);return}
  area.innerHTML='<div class="mfa-box"><h3>Beskytt arbeidskontoen</h3><p>Sett opp Authenticator før rolledata åpnes.</p><button id="startMfa" class="ghost" type="button">Sett opp Authenticator</button></div>';$('#startMfa').addEventListener('click',startMfa);
}
async function startMfa(){const area=$('#mfaArea');const {data,error}=await client.auth.mfa.enroll({factorType:'totp',friendlyName:'AidMe VIDA',issuer:'AidMe'});if(error){show('Kunne ikke starte tofaktor',error.message);return}factor={id:data.id,existing:false};area.innerHTML=`<div class="mfa-box"><h3>Skann i Authenticator</h3><p>Skann QR-koden eller legg inn nøkkelen manuelt. Skriv deretter inn seks-sifret kode.</p><img src="${esc(data.totp.qr_code)}" alt="QR-kode for AidMe VIDA Authenticator"><code>${esc(data.totp.secret)}</code><div class="mfa-row"><label><span>Kode</span><input id="mfaCode" inputmode="numeric" autocomplete="one-time-code" maxlength="6"></label><button id="verifyMfa" class="primary" type="button">Aktiver</button></div><p id="mfaMessage" class="message"></p></div>`;$('#verifyMfa').addEventListener('click',verifyMfa)}
async function verifyMfa(){const code=String($('#mfaCode')?.value||'').replace(/\s/g,'');const msg=$('#mfaMessage');if(!/^\d{6}$/.test(code)){msg.textContent='Skriv inn seks sifre.';return}msg.textContent='Bekrefter…';const challenge=await client.auth.mfa.challenge({factorId:factor.id});if(challenge.error){msg.textContent='Kunne ikke opprette sikkerhetskontroll.';return}const verify=await client.auth.mfa.verify({factorId:factor.id,challengeId:challenge.data.id,code});if(verify.error){msg.textContent='Koden ble ikke godkjent. Prøv neste kode fra Authenticator.';return}await refreshMfa()}
$('#profileForm').addEventListener('submit',async e=>{e.preventDefault();hideMessage();const btn=e.submitter;btn.disabled=true;btn.textContent='Lagrer…';try{const body={action:'UPDATE',display_name:$('#displayName').value,phone:$('#phone').value,locale:$('#locale').value};if(state.accountType==='participant'){body.birth_year=$('#birthYear').value||null;body.preferred_contact_method=$('#preferredContact').value}else body.job_title=$('#jobTitle').value;const result=await invoke(body);$('#profileMessage').textContent='Profilen er lagret.';await init(true);if(result.next==='ACCESS_PENDING')show('Profilen er klar','Administrator må tildele arbeidsrolle før arbeidsflaten åpnes.')}catch(err){$('#profileMessage').textContent=`Kunne ikke lagre: ${err.message}`}finally{btn.disabled=false;btn.textContent='Lagre og fortsett'}});
async function init(quiet=false){const {data:{session}}=await client.auth.getSession();if(!session){$('#sessionPill').textContent='Invitasjon · mangler økt';show('Invitasjonslenken kan ikke brukes','Denne lenken er utløpt, allerede brukt eller mangler en gyldig innloggingsøkt. Be om en ny invitasjon eller gå tilbake til AidMe VIDA-innloggingen for dette miljøet.');return}try{const data=await invoke({action:'GET'});fill(data);if(!quiet&&location.hash)history.replaceState(null,'',location.pathname+location.search)}catch(err){show('Kunne ikke åpne profilen','Økten er gyldig, men profilen kunne ikke klargjøres. Ingen opplysninger er endret.')}}
init();