name: ci-baseline
on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect Node project
        id: detect
        shell: bash
        run: |
          if [ -f package.json ]; then echo "has_node=true" >> "$GITHUB_OUTPUT"; else echo "has_node=false" >> "$GITHUB_OUTPUT"; fi

      - name: Setup Node
        if: steps.detect.outputs.has_node == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        if: steps.detect.outputs.has_node == 'true'
        run: npm ci

      - name: Lint (no-op if missing)
        if: steps.detect.outputs.has_node == 'true'
        run: npm run -s lint || echo "no lint script"

      - name: Test (no-op if missing)
        if: steps.detect.outputs.has_node == 'true'
        run: npm test --if-present

      - name: Build (no-op if missing)
        if: steps.detect.outputs.has_node == 'true'
        run: npm run build --if-present
