name: ps-ci
on:
  pull_request:

jobs:
  ps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PowerShell CI
        shell: pwsh
        run: |
          pwsh -v
          ./tools/ci.ps1
